# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: pandoc/core

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build resume
        shell: sh
        run: |
          pandoc --standalone -H style_chmduquesne.css --from markdown --to html -o resume.html resume.md
      - name: save
        uses: actions/upload-artifact@v2
        with:
          name: resumehtml
          path: resume.html
  publish:
    runs-on: ubuntu-latest
    container: alpine/git
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: resumehtml
      - name: publish
        shell: sh
        run: |
          nslookup github.com
          env
          git config --global user.email "rob.petti@gmail.com"
          git config --global user.name "Rob Petti"
          CHECKOUT_DIR=$(mktemp -d)
          git clone --single-branch --branch master "https://rpetti:${{secrets.API_TOKEN}}@github.com/rpetti/rpetti.github.io.git/" $CHECKOUT_DIR
          cp resume.html $CHECKOUT_DIR/resume.html
          cd $CHECKOUT_DIR
          git commit -a -m "auto updating resume.html"
          git push "https://rpetti:${{secrets.API_TOKEN}}@github.com/rpetti/rpetti.github.io.git/" master
        
          
          
